version: '3.8'
services:
  cli:
    build:
      target: local_app
      dockerfile: cli/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    container_name: "${COMPOSE_PROJECT_NAME}_cli"
    tty: true
    stdin_open: true
    env_file:
      - ../../.env
    ports:
      - "${HTTP_EXTERNAL_PORT}:8080"
      - "${DELVE_EXTERNAL_PORT}:40000"
    volumes:
      - ./../../:/go/src/app
    depends_on:
      - db
  db:
    image: postgres:12.1
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    command: postgres -c logging_collector=on -c log_directory=/var/lib/pg_log -c log_filename=postgresql.log -c log_statement=all
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./../data/logs:/var/lib/pg_log
    env_file:
      - ../../.env

volumes:
  pgdata:
    driver: local
