version: '3.8'
services:
  cli:
    build:
      target: local_app
      dockerfile: cli/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    container_name: "${COMPOSE_PROJECT_NAME}_cli"
    tty: true
    stdin_open: true
    env_file:
      - ../../.env
    ports:
      - "${HTTP_EXTERNAL_PORT}:8080"
      - "${DELVE_EXTERNAL_PORT}:40000"
    volumes:
      - ./../../:/go/src/app
